spring:
  application:
    name: payment
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: all
      retries: 2147483647
      batch-size: 131072
      compression-type: zstd
      # tudo que Ã© "config Kafka puro" vai aqui em properties.*
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 10
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000

app:
  kafka:
    topic: ${APP_KAFKA_TOPIC:payments.authorize.in}

